version: "3.8"
services:
  webphone_node:
    build: .
    ports:
      - "8081:8081"
    # Map files which could change during development for hot reload support
    container_name: webphone_node
    env_file:
      - "./.env"
    volumes:
      - ./src:/app/src
      - webphone_node_node_modules:/app/node_modules
volumes:
  webphone_node_node_modules:
