default: &default
  appUrl: http://localhost:3001
  webphoneUrl: http://localhost:3000
  wsUrl: ws://localhost:8081
  host: https://ns32.lab4thinking.fr/bigbluebutton/api
  bbb_secret: 7f0f55ef18b9aaeab482b772397cdad6
  voipHost: 127.0.0.1
  outputPath: public/assets
  compilerHashType: hash
  compilerDevtool: cheap-module-source-map
  webpackMode: development
  minimizeAssets: false
  publicPath: /assets/
  manifestFilename: webpack.manifest.json
  secretToken: d371dbef7aa52d1f70437c9a20371615c6788c2e4dde5cb6a41e3ff4e1cdd05f8ca3f586bb19aad8a31d442f6ecc38551c49ea7fcf2c06b459921b7b8733b384
  webphoneCheckUrl: https://localhost:3000
  browserMinimalVersion:
    Chrome: 80
    Safari: 13
    Firefox: 78
    Edge: 80
  systemMinimalVersion:
    MacOS: 10.13
    iOS: 13.0
    Android: 9
    Windows: 7
  terms:
    regularTerms: https://en.ibridgepeople.com/utilisation
    interpreterTerms: https://en.ibridgepeople.com/utilisation
    moderatorTerms: https://en.ibridgepeople.com/utilisation

development:
  <<: *default

remote: &remote
  <<: *default
  compilerHashType: chunkhash
  compilerDevtool: false
  webpackMode: production
  minimizeAssets: true

docker:
  <<: *default
  appUrl: https://webphone.tech
  webphoneUrl: https://webphone.tech/fs
  wsUrl: wss://webphone.tech/ws

old_production:
  <<: *remote
  appUrl: https://webphone10.ibridgepeople.net
  webphoneUrl: https://webphone10.ibridgepeople.net/fs
  wsUrl: wss://webphone10.ibridgepeople.net/ws
  voipHost: 163.172.225.179
  webphoneCheckUrl: https://stg-check.meeting.ibridgepeople.net/

staging:
  <<: *remote
  appUrl: https://stg.meeting.ibridgepeople.net
  webphoneUrl: https://stg.meeting.ibridgepeople.net/fs
  wsUrl: wss://stg.meeting.ibridgepeople.net/ws
  voipHost: 192.168.1.110
  webphoneCheckUrl: https://stg-check.meeting.ibridgepeople.net/

bench:
  <<: *remote
  appUrl: https://meeting.ibridgepeople.fr
  webphoneUrl: https://meeting.ibridgepeople.fr/fs
  wsUrl: wss://meeting.ibridgepeople.fr/ws
  voipHost: 192.168.1.110
  webphoneCheckUrl: https://webphone.ibrigepeople.fr/test

production:
  <<: *remote
  appUrl: https://webphone.ibridgepeople.fr
  webphoneUrl: https://webphone.ibridgepeople.fr/fs
  wsUrl: wss://webphone.ibridgepeople.fr/ws
  voipHost: 192.168.1.110
  webphoneCheckUrl: https://webphone.ibrigepeople.fr/test